# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripci\xf3n')),
                ('fecha_de_ejecucion', models.DateField()),
                ('repetir_cada', models.TextField(default=0)),
                ('unidad_de_repeticion', models.IntegerField(blank=True, choices=[(3, 'Mes(es)'), (4, 'A\xf1o(s)')], default=3, null=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipo de actividades',
            },
        ),
    ]
