# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objeto', models.TextField(max_length=400, verbose_name='Objeto de la reuni\xf3n')),
                ('fecha_de_ejecucion', models.DateField()),
                ('repetir_cada', models.TextField(default=0)),
                ('unidad_de_repeticion', models.IntegerField(blank=True, choices=[(3, 'Mes(es)'), (4, 'A\xf1o(s)')], default=3, null=True)),
            ],
            options={
                'verbose_name': 'Reuni\xf3n',
                'verbose_name_plural': 'Reuniones',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de reuni\xf3n',
                'verbose_name_plural': 'Tipo de reuniones',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Lugar'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_de_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoActividad', verbose_name='Tipo de reunion'),
        ),
    ]
