# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_merge_20160907_0341'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='departamentos',
            field=models.ManyToManyField(to='personal.Departamento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='personas',
            field=models.ManyToManyField(to='personal.Persona'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='repetir_cada',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
