# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20160906_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Reuni\xf3n', 'verbose_name_plural': 'Reuniones'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'Tipo de reuni\xf3n', 'verbose_name_plural': 'Tipo de reuniones'},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='objeto',
            field=models.TextField(default=' ', max_length=400, verbose_name='Objeto de la reuni\xf3n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_de_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoActividad', verbose_name='Tipo de reunion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Lugar'),
        ),
    ]
