# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20160906_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='equipo',
            new_name='personal',
        ),
    ]
