# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudadanos', '0002_auto_20160906_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.FileField(upload_to='cedula', verbose_name='Copia ampliada (150) de la cedula de ciudadania')),
                ('foto', models.ImageField(upload_to='foto')),
                ('tramitado', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadanos.Ciudadano')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.FileField(upload_to='diploma', verbose_name='Copia del diploma')),
                ('acta', models.FileField(upload_to='acta', verbose_name='Copia del acta de grado')),
                ('cedula', models.FileField(upload_to='cedula', verbose_name='Copia ampliada (150) de la cedula de ciudadania')),
                ('tramitado', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadanos.Ciudadano')),
            ],
            options={
                'verbose_name': 'Registro Profecionale(que no hacen rural)',
                'verbose_name_plural': 'Registros Profecionales(que no hacen rural)',
            },
        ),
        migrations.CreateModel(
            name='RegistroProS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.FileField(upload_to='diploma', verbose_name='Copia del diploma')),
                ('acta', models.FileField(upload_to='acta', verbose_name='Copia del acta de grado')),
                ('cedula', models.FileField(upload_to='cedula', verbose_name='Copia ampliada (150) de la cedula de ciudadania')),
                ('resolucion', models.FileField(upload_to='resolucion', verbose_name='resolucion de nombramiento del servicio social obligatorio')),
                ('rural', models.FileField(upload_to='rural', verbose_name='Acta posesion del rural')),
                ('certificado', models.FileField(upload_to='certificado', verbose_name='Certificado de culiminacion del a\xf1o rural')),
                ('tramitado', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadanos.Ciudadano')),
            ],
            options={
                'verbose_name': 'Registro Profecional',
                'verbose_name_plural': 'Registros Profecionales',
            },
        ),
        migrations.CreateModel(
            name='TarjetaPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.FileField(upload_to='registro', verbose_name='Registro profesional')),
                ('cedula', models.FileField(upload_to='cedula', verbose_name='Copia ampliada (150) de la cedula de ciudadania')),
                ('sellos', models.FileField(upload_to='sellos', verbose_name='Copia de los sellos del diploma')),
                ('tramitado', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadanos.Ciudadano')),
            ],
            options={
                'verbose_name': 'RP Odontologos \u2013 bacteriologos \u2013 enfermeros \u2013 medicos \u2013 fisioterapeutas \u2013 istrumentadores quirurgicos y auxiliares en general',
                'verbose_name_plural': 'RP Odontologos \u2013 bacteriologos \u2013 enfermeros \u2013 medicos \u2013 fisioterapeutas \u2013 istrumentadores quirurgicos y auxiliares en general',
            },
        ),
    ]
