# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetapro',
            options={'verbose_name': 'Tarjeta Profesional', 'verbose_name_plural': 'Tarjetas Profecionales'},
        ),
    ]
