# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0003_auto_20160906_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pregusta', models.CharField(max_length=2000)),
                ('respuesta', models.CharField(max_length=2000)),
                ('state', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Cargo')),
            ],
        ),
    ]
