# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pregunta', models.CharField(max_length=2000)),
                ('respuesta', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Departamento')),
            ],
            options={
                'verbose_name': 'Pregusta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
