# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160906_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregusta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='pregusta',
            new_name='pregunta',
        ),
    ]
