# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20160906_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
