# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20160907_0020'),
        ('personal', '0002_auto_20160907_0001'),
    ]

    operations = [
    ]
