# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_merge_20160907_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.Cargo'),
            preserve_default=False,
        ),
    ]
