# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_merge_20160908_0233'),
        ('personal', '0004_auto_20160907_1440'),
    ]

    operations = [
    ]
